name: Android example build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: kuhnroyal/flutter-fvm-config-action@v3
      - run: fvm flutter pub get
        working-directory: example
      - run: fvm flutter build apk
        working-directory: example
      - uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            example/build/app/outputs/flutter-apk/app-release.apk
