name: Analyze

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

jobs:
  windows-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v3
      - run: |
          flutter pub get
          flutter analyze
