name: iOS example build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v3
      - run: flutter pub get
        working-directory: example
      - run: flutter build ios --release --no-codesign
        working-directory: example
      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            example/build/ios/iphoneos/Runner.app
