name: MacOS example build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [master]

jobs:
  macos-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v3
      - run: fvm flutter config --enable-macos-desktop
        working-directory: example
      - run: fvm flutter build macos
        working-directory: example
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            example/build/macos/Build/Products/Release/flutter_nsd_example.app
